version: '3.9'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: cccat16
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: cccat16_password
    volumes:
      - ./ccca_data:/var/lib/postgresql/data
volumes:
  ccca_data: