name: exercicio_aula1
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  postgres: ^3.1.2
  uuid: ^4.3.3
  get_it: ^7.6.8
  injectable: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.9
  hard_analyser: ^1.9.0
  # strict: ^2.1.0
  http: ^1.1.0
  injectable_generator: ^2.6.1
  shelf_router_generator: ^1.1.0
  test: ^1.24.0
